name: Release and Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: 'cr.yandex/${{ secrets.CR_REGISTRY }}/${{ github.event.repository.name }}'
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Copy pem file
        run: |
          echo "${{ secrets.JWT_PUBLIC_KEY_PEM }}" > key.pem
      - name: Login to Docker Hub
        uses: yc-actions/yc-cr-login@v3
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_CR_IMAGES_PUSHER }}
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        run: |
          docker buildx build --pull \
            --build-arg GITHUB_SHA \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:$GITHUB_SHA .
          docker push $IMAGE_NAME --all-tags
      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v5
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_CR_IMAGES_PUSHER }}
          container-name: ${{ github.event.repository.name }}
          folder-id: b1gi7gh5bmam7ibes1f5
          revision-service-account-id: ajegbbm8df1ogq00du1f
          revision-cores: 1
          revision-memory: 128Mb
          revision-core-fraction: 100
          revision-concurrency: 1
          revision-image-url: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          revision-execution-timeout: 10
          revision-env: |
            JWT_PUBLIC_KEY_FILE=key.pem
            JWT_ISSUER=iis
            JWT_AUDIENCE=aud
            LOCKBOX_SECRET_ID=e6qnvpm2mppmdfrgkk5m
            RESTY_DEBUG=true
            LOCKBOX_SECRET_JSON={"timconsult": {"token":"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjY3MDQwMGE3Zjk5OTUyMWE5YjIzODY4ZGFlY2VlNzMzNDJlZDA1YTY1N2I4OWFlY2FhNTNlZTE1MzFlODE5NmYyOGRlZjA5NjNiMjg5OWFiIn0.eyJhdWQiOiIxOGE1NjU3NC1iNmI4LTQ5MmQtOTVhOC0wZDk0YzY1ODczNzUiLCJqdGkiOiI2NzA0MDBhN2Y5OTk1MjFhOWIyMzg2OGRhZWNlZTczMzQyZWQwNWE2NTdiODlhZWNhYTUzZWUxNTMxZTgxOTZmMjhkZWYwOTYzYjI4OTlhYiIsImlhdCI6MTc3NTgzMDc5MiwibmJmIjoxNzc1ODMwNzkyLCJleHAiOjE3OTg2NzUyMDAsInN1YiI6IjEyODg1NzQ2IiwiZ3JhbnRfdHlwZSI6IiIsImFjY291bnRfaWQiOjI4ODk2MjUzLCJiYXNlX2RvbWFpbiI6ImFtb2NybS5ydSIsInZlcnNpb24iOjIsInNjb3BlcyI6WyJwdXNoX25vdGlmaWNhdGlvbnMiLCJmaWxlcyIsImNybSIsImZpbGVzX2RlbGV0ZSIsIm5vdGlmaWNhdGlvbnMiXSwiaGFzaF91dWlkIjoiMTRiMmJlZWQtMjk3Mi00MmNiLTg0MTMtZDI3MTI0MzZhMjg5IiwiYXBpX2RvbWFpbiI6ImFwaS1iLmFtb2NybS5ydSJ9.ERPqh8rYVZJvHaxI9gqJ0GS-bunR0Kmfa0exRMMXi9mluyvveQC8KUbdyekOcq-DPRnqhefv0coLNqWn8CuAloAuTHJM5csx5a-3z2Hwb7bDOxKrusCUqdP9YWi5Oiqhwp0h4oN5zlLu8yhnjczVNBbmcd3mvEgYTLYMDaaS0k_KigfVHjiPLQG13_G57TT7qT_qKAx6_LgG22ph8Vrc_QBwMqyIs5_WB8GP9qy7y60kArYKMGoSoYOyWHHE9_Z84HsmnNJmCHCxgD4QzC7lVb5lOt3M-qxrh1RJv5iQ-fZpsKA4xNdL-hIJZWbqqohiw6AiGUhE4eom3IBiHqsEaA","rps": 5}}